### ISSUE TITLE
Docker container - OpenAI

### ISSUE THREAD

**Issue by UFOSmuggler** [Librum-Reader/Librum-Server#13]
G'day,

Thanks for all your work so far, seems to be a good body of work.

I'd like to ask you to assist with using the OpenAI explain feature for a self-hosted docker container setup.  I assumed that OpenAIToken api key would be picked up as an environment variable but I cannot confirm so far. 

I have specified my token as the env var OpenAIToken in the container, but when I attempt to use the explain function I receive no response in the reader, see an exception in the librum-server logs, and also see that the "last used" date on my openai api key doesn't change from "never".

This is the exception seen in librum-server:

```
2023-11-22T02:48:56.988507919Z warn: Application.Services.AiService[0]
2023-11-22T02:48:56.988527191Z       Ai explanation failed
2023-11-22T02:48:56.988795500Z warn: Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor[2]
2023-11-22T02:48:56.988808790Z       No output formatter was found for content types 'text/event-stream, text/event-stream' to write the response.
2023-11-22T02:48:56.989641273Z fail: Application.Common.Middleware.ExceptionHandlingMiddleware[0]
2023-11-22T02:48:56.989655753Z       StatusCode cannot be set because the response has already started.
2023-11-22T02:48:56.989660034Z       System.InvalidOperationException: StatusCode cannot be set because the response has already started.
2023-11-22T02:48:56.989663668Z          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ThrowResponseAlreadyStartedException(String value)
2023-11-22T02:48:56.989667471Z          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.Microsoft.AspNetCore.Http.Features.IHttpResponseFeature.set_StatusCode(Int32 value)
2023-11-22T02:48:56.989671172Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.ExecuteAsyncCore(ActionContext context, ObjectResult result, Type objectType, Object value)
2023-11-22T02:48:56.989674826Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
2023-11-22T02:48:56.989678867Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
2023-11-22T02:48:56.989682452Z       --- End of stack trace from previous location ---
2023-11-22T02:48:56.989685821Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
2023-11-22T02:48:56.989689016Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
2023-11-22T02:48:56.989705245Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
2023-11-22T02:48:56.989708675Z       --- End of stack trace from previous location ---
2023-11-22T02:48:56.989711818Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2023-11-22T02:48:56.989715608Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
2023-11-22T02:48:56.989718518Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2023-11-22T02:48:56.989722975Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2023-11-22T02:48:56.989726520Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2023-11-22T02:48:56.989730227Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2023-11-22T02:48:56.989734105Z          at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
2023-11-22T02:48:56.989738363Z          at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
2023-11-22T02:48:56.989741647Z          at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
2023-11-22T02:48:56.989744846Z          at Application.Common.Middleware.ExceptionHandlingMiddleware.InvokeAsync(HttpContext context) in /app/src/Application/Common/Middleware/ExceptionHandlingMiddleware.cs:line 47
2023-11-22T02:48:56.990027927Z fail: Microsoft.AspNetCore.Server.Kestrel[13]
2023-11-22T02:48:56.990035839Z       Connection id "0HMVAVOH11A06", Request id "0HMVAVOH11A06:00000085": An unhandled exception was thrown by the application.
2023-11-22T02:48:56.990038672Z       System.InvalidOperationException: Headers are read-only, response has already started.
2023-11-22T02:48:56.990040937Z          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ThrowHeadersReadOnlyException()
2023-11-22T02:48:56.990043220Z          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseHeaders.Microsoft.AspNetCore.Http.IHeaderDictionary.set_ContentType(StringValues value)
2023-11-22T02:48:56.990045621Z          at Microsoft.AspNetCore.Http.DefaultHttpResponse.set_ContentType(String value)
2023-11-22T02:48:56.990047842Z          at Application.Common.Middleware.ExceptionHandlingMiddleware.InvokeAsync(HttpContext context) in /app/src/Application/Common/Middleware/ExceptionHandlingMiddleware.cs:line 47
2023-11-22T02:48:56.990050256Z          at AspNetCoreRateLimit.RateLimitMiddleware`1.Invoke(HttpContext context) in C:\Users\User\Documents\Github\AspNetCoreRateLimit\src\AspNetCoreRateLimit\Middleware\RateLimitMiddleware.cs:line 125
2023-11-22T02:48:56.990061477Z          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

I appreciate any assistance you can provide.

**Comment by DavidLazarescu** [comment]
have you tried adding the OpenAI key to the configuration file? That should work, you should not need to manually expose it as an environment variable

**Comment by UFOSmuggler** [comment]
Hi @DavidLazarescu, thanks for responding mate.

In the docker container I do not believe there is a librum configuration file, I am pretty sure it gets everything from env vars:

```bash
$ docker exec -it -u root librum find / -name "*.conf"|grep -v Permission
/usr/share/libc-bin/nsswitch.conf
/usr/share/adduser/adduser.conf
/usr/share/debconf/debconf.conf
/usr/lib/tmpfiles.d/passwd.conf
/etc/security/faillock.conf
/etc/security/group.conf
/etc/security/limits.conf
/etc/security/sepermit.conf
/etc/security/time.conf
/etc/security/pam_env.conf
/etc/security/namespace.conf
/etc/security/access.conf
/etc/host.conf
/etc/nsswitch.conf
/etc/gai.conf
/etc/xattr.conf
/etc/e2scrub.conf
/etc/ld.so.conf
/etc/pam.conf
/etc/deluser.conf
/etc/selinux/semanage.conf
/etc/debconf.conf
/etc/resolv.conf
/etc/adduser.conf
/etc/libaudit.conf
/etc/mke2fs.conf
/etc/ld.so.conf.d/x86_64-linux-gnu.conf
/etc/ld.so.conf.d/libc.conf
/etc/ca-certificates.conf
```

I'm guessing it DOES pick it up from the env var because if I do not supply the env var, the librum reader says I have reached my limit when attempting to run an explain.  As an aside, [the URL mentioned in the error](https://librumreader.com/whyAiLimits) does not exist.

As the behaviour differs between having and not having the env var, I assume it is in fact picking it up, and that the error in my initial post stems from something else.

Thanks for your assistance mate.

**Comment by UFOSmuggler** [comment]
Actually, this turns out just to be what happens when you have insufficient quota remaining on the api key.

Here's the response body that openai returns when that happens:

```json
{
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}
```

Perhaps this could be used to return a better error from the application.

Closing since there is no problem, thanks for assisting.

**Comment by DavidLazarescu** [comment]
Ah, that is a mistake on my side then. The self hosted version obviously should have no quota. Also, it should be fairly obvious when a "quota exceeded error" occurs, it should say so in the application.
